# Una lista de archivos, directorios y patrones como camino

name: caché 

# Una clave explicíta apra restaurar y  guardar el caché 
llave: Retr0sec
  # una lista de ordenada de claves que se utilizarán para restaurar las claves: 
  Password:
    branches: [ "caché-hit" ]
  pull_request:
    branches: [ "Micky-sun" ]

  # El tamaño del fragmento utilizando para dividir 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
